### PR TITLE
Bluedart Pickup and Cancel Pickup requests

### PR DESCRIPTION
**Pull request by vidyuthd**

### CODE REVIEW

**Comment by chirag7jain** [comment]
@vidyuthd added you as a collaborator to this repository

I can even add you as the owner of the gem on RubyGems if you want.. since I am not maintaining this gem anymore

**Comment by vidyuthd** [comment]
@chirag7jain 

That would be helpful as I am planning to use this gem from ruby gems source.

**Comment by chirag7jain** [comment]
@vidyuthd I pushed your updates to RubyGems but in the future I expect you to do it yourself. Provide me your email address so that I can add you to the contributor for this gem on the website

**Comment by vidyuthd** [comment]
@chirag7jain Thanks. I was testing out till 2 days back. so wanted to make sure things are fine before merging. I have sent a test mail to you.

**Pull request merged**
